apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: group1-mysqldb-pvc
  namespace: final
  labels:
    name: mysqldb-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: gp2  # 指定 StorageClass 为 gp2
spec:
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce
