apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: CLO835-role-binding
  namespace: final 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: CLO835 
subjects:
- namespace: final        # 确保这个是 ServiceAccount 所在的命名空间
  kind: ServiceAccount
  name: clo835